#  docker-compose up
#  docker ps
#  docker exec -it zio-rite-of-passage-db-1 psql -U docker
#  \c demodb
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"